
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package fr.eseo.gestionparking;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-04-03T00:17:55.101+02:00
 * Generated source version: 3.2.2
 *
 */

@javax.jws.WebService(
                      serviceName = "GestionParkingService",
                      portName = "GestionParkingPort",
                      targetNamespace = "http://gestionparking.eseo.fr/",
                      wsdlLocation = "http://localhost:8080/GestionParkingSW/services/GestionParkingPort?wsdl",
                      endpointInterface = "fr.eseo.gestionparking.GestionParkingSEI")

public class GestionParkingPortImpl implements GestionParkingSEI {

    private static final Logger LOG = Logger.getLogger(GestionParkingPortImpl.class.getName());

    /* (non-Javadoc)
     * @see fr.eseo.gestionparking.GestionParkingSEI#payerParking(int arg0)*
     */
    public java.lang.String payerParking(int arg0) {
        LOG.info("Executing operation payerParking");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-88374902";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.gestionparking.GestionParkingSEI#trouverParking(fr.eseo.gestionparking.Parking arg0)*
     */
    public java.util.List<fr.eseo.gestionparking.Parking> trouverParking(fr.eseo.gestionparking.Parking arg0) {
        LOG.info("Executing operation trouverParking");
        System.out.println(arg0);
        try {
            java.util.List<fr.eseo.gestionparking.Parking> _return = new java.util.ArrayList<fr.eseo.gestionparking.Parking>();
            fr.eseo.gestionparking.Parking _returnVal1 = new fr.eseo.gestionparking.Parking();
            _returnVal1.setAdresse("Adresse1744045824");
            _returnVal1.setCode(763973331);
            _returnVal1.setNom("Nom-1818625833");
            _returnVal1.setPrixBase(0.45200968f);
            _returnVal1.setType("Type-293187722");
            _returnVal1.setVille("Ville-2091952844");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.gestionparking.GestionParkingSEI#reserverParking(fr.eseo.gestionparking.ReservationParking arg0)*
     */
    public int reserverParking(fr.eseo.gestionparking.ReservationParking arg0) {
        LOG.info("Executing operation reserverParking");
        System.out.println(arg0);
        try {
            int _return = 561429284;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.gestionparking.GestionParkingSEI#annulerParking(int arg0)*
     */
    public boolean annulerParking(int arg0) {
        LOG.info("Executing operation annulerParking");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
