package fr.eseo.gestionparking;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-04-03T00:17:55.121+02:00
 * Generated source version: 3.2.2
 *
 */
@WebServiceClient(name = "GestionParkingService",
                  wsdlLocation = "http://localhost:8080/GestionParkingSW/services/GestionParkingPort?wsdl",
                  targetNamespace = "http://gestionparking.eseo.fr/")
public class GestionParkingService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://gestionparking.eseo.fr/", "GestionParkingService");
    public final static QName GestionParkingPort = new QName("http://gestionparking.eseo.fr/", "GestionParkingPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/GestionParkingSW/services/GestionParkingPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GestionParkingService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/GestionParkingSW/services/GestionParkingPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GestionParkingService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GestionParkingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionParkingService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GestionParkingService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GestionParkingService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GestionParkingService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GestionParkingSEI
     */
    @WebEndpoint(name = "GestionParkingPort")
    public GestionParkingSEI getGestionParkingPort() {
        return super.getPort(GestionParkingPort, GestionParkingSEI.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionParkingSEI
     */
    @WebEndpoint(name = "GestionParkingPort")
    public GestionParkingSEI getGestionParkingPort(WebServiceFeature... features) {
        return super.getPort(GestionParkingPort, GestionParkingSEI.class, features);
    }

}
