package fr.eseo.gestionparking;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-04-03T00:17:55.114+02:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://gestionparking.eseo.fr/", name = "GestionParkingSEI")
@XmlSeeAlso({ObjectFactory.class})
public interface GestionParkingSEI {

    @WebMethod(action = "urn:PayerParking")
    @RequestWrapper(localName = "payerParking", targetNamespace = "http://gestionparking.eseo.fr/", className = "fr.eseo.gestionparking.PayerParking")
    @ResponseWrapper(localName = "payerParkingResponse", targetNamespace = "http://gestionparking.eseo.fr/", className = "fr.eseo.gestionparking.PayerParkingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String payerParking(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod(action = "urn:TrouverParking")
    @RequestWrapper(localName = "trouverParking", targetNamespace = "http://gestionparking.eseo.fr/", className = "fr.eseo.gestionparking.TrouverParking")
    @ResponseWrapper(localName = "trouverParkingResponse", targetNamespace = "http://gestionparking.eseo.fr/", className = "fr.eseo.gestionparking.TrouverParkingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<fr.eseo.gestionparking.Parking> trouverParking(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.gestionparking.Parking arg0
    );

    @WebMethod(action = "urn:ReserverParking")
    @RequestWrapper(localName = "reserverParking", targetNamespace = "http://gestionparking.eseo.fr/", className = "fr.eseo.gestionparking.ReserverParking")
    @ResponseWrapper(localName = "reserverParkingResponse", targetNamespace = "http://gestionparking.eseo.fr/", className = "fr.eseo.gestionparking.ReserverParkingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int reserverParking(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.gestionparking.ReservationParking arg0
    );

    @WebMethod(action = "urn:AnnulerParking")
    @RequestWrapper(localName = "annulerParking", targetNamespace = "http://gestionparking.eseo.fr/", className = "fr.eseo.gestionparking.AnnulerParking")
    @ResponseWrapper(localName = "annulerParkingResponse", targetNamespace = "http://gestionparking.eseo.fr/", className = "fr.eseo.gestionparking.AnnulerParkingResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean annulerParking(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
