
package fr.eseo.gestionparking;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-04-03T00:17:55.036+02:00
 * Generated source version: 3.2.2
 *
 */
public final class GestionParkingSEI_GestionParkingPort_Client {

    private static final QName SERVICE_NAME = new QName("http://gestionparking.eseo.fr/", "GestionParkingService");

    private GestionParkingSEI_GestionParkingPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GestionParkingService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        GestionParkingService ss = new GestionParkingService(wsdlURL, SERVICE_NAME);
        GestionParkingSEI port = ss.getGestionParkingPort();

        {
        System.out.println("Invoking payerParking...");
        int _payerParking_arg0 = 1485318937;
        java.lang.String _payerParking__return = port.payerParking(_payerParking_arg0);
        System.out.println("payerParking.result=" + _payerParking__return);


        }
        {
        System.out.println("Invoking trouverParking...");
        fr.eseo.gestionparking.Parking _trouverParking_arg0 = new fr.eseo.gestionparking.Parking();
        _trouverParking_arg0.setAdresse("Adresse724427391");
        _trouverParking_arg0.setCode(-985406243);
        _trouverParking_arg0.setNom("Nom2022066092");
        _trouverParking_arg0.setPrixBase(0.34584653f);
        _trouverParking_arg0.setType("Type1975135937");
        _trouverParking_arg0.setVille("Ville477484296");
        java.util.List<fr.eseo.gestionparking.Parking> _trouverParking__return = port.trouverParking(_trouverParking_arg0);
        System.out.println("trouverParking.result=" + _trouverParking__return);


        }
        {
        System.out.println("Invoking reserverParking...");
        fr.eseo.gestionparking.ReservationParking _reserverParking_arg0 = new fr.eseo.gestionparking.ReservationParking();
        _reserverParking_arg0.setCodeClient(-1057601129);
        _reserverParking_arg0.setCodeParking(-198191706);
        _reserverParking_arg0.setCodeResa(34923690);
        _reserverParking_arg0.setDateDebut(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-04-03T00:17:55.098+02:00"));
        _reserverParking_arg0.setDateFin(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-04-03T00:17:55.099+02:00"));
        _reserverParking_arg0.setPaiement(false);
        int _reserverParking__return = port.reserverParking(_reserverParking_arg0);
        System.out.println("reserverParking.result=" + _reserverParking__return);


        }
        {
        System.out.println("Invoking annulerParking...");
        int _annulerParking_arg0 = -633293128;
        boolean _annulerParking__return = port.annulerParking(_annulerParking_arg0);
        System.out.println("annulerParking.result=" + _annulerParking__return);


        }

        System.exit(0);
    }

}
