
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package fr.eseo.javaee.projet.visiteguidee;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-26T10:02:56.205+02:00
 * Generated source version: 3.2.2
 *
 */

@javax.jws.WebService(
                      serviceName = "ReservationVisiteService",
                      portName = "ReservationVisitePort",
                      targetNamespace = "http://visiteguidee.projet.javaee.eseo.fr/",
                      wsdlLocation = "http://localhost:8080/GestionVisites/services/ReservationVisitePort?wsdl",
                      endpointInterface = "fr.eseo.javaee.projet.visiteguidee.ReservationVisiteSEI")

public class ReservationVisitePortImpl implements ReservationVisiteSEI {

    private static final Logger LOG = Logger.getLogger(ReservationVisitePortImpl.class.getName());

    /* (non-Javadoc)
     * @see fr.eseo.javaee.projet.visiteguidee.ReservationVisiteSEI#reserverVisite(fr.eseo.javaee.projet.visiteguidee.Reservation arg0)*
     */
    public int reserverVisite(fr.eseo.javaee.projet.visiteguidee.Reservation arg0) throws SQLException_Exception   {
        LOG.info("Executing operation reserverVisite");
        System.out.println(arg0);
        try {
            int _return = 332545327;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SQLException_Exception("SQLException...");
    }

    /* (non-Javadoc)
     * @see fr.eseo.javaee.projet.visiteguidee.ReservationVisiteSEI#payerVisite(int arg0)*
     */
    public boolean payerVisite(int arg0) throws SQLException_Exception   {
        LOG.info("Executing operation payerVisite");
        System.out.println(arg0);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SQLException_Exception("SQLException...");
    }

    /* (non-Javadoc)
     * @see fr.eseo.javaee.projet.visiteguidee.ReservationVisiteSEI#trouverVisite(fr.eseo.javaee.projet.visiteguidee.Visite arg0)*
     */
    public java.util.List<fr.eseo.javaee.projet.visiteguidee.Visite> trouverVisite(fr.eseo.javaee.projet.visiteguidee.Visite arg0) throws SQLException_Exception   {
        LOG.info("Executing operation trouverVisite");
        System.out.println(arg0);
        try {
            java.util.List<fr.eseo.javaee.projet.visiteguidee.Visite> _return = new java.util.ArrayList<fr.eseo.javaee.projet.visiteguidee.Visite>();
            fr.eseo.javaee.projet.visiteguidee.Visite _returnVal1 = new fr.eseo.javaee.projet.visiteguidee.Visite();
            _returnVal1.setCodeVisite(-34604151);
            _returnVal1.setDateVisite(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-03-26T10:02:56.221+02:00"));
            _returnVal1.setPrix(0.44048065f);
            _returnVal1.setTypeDeVisite("TypeDeVisite157604872");
            _returnVal1.setVille("Ville538354914");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SQLException_Exception("SQLException...");
    }

    /* (non-Javadoc)
     * @see fr.eseo.javaee.projet.visiteguidee.ReservationVisiteSEI#annulerVisite(int arg0)*
     */
    public boolean annulerVisite(int arg0) throws SQLException_Exception   {
        LOG.info("Executing operation annulerVisite");
        System.out.println(arg0);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SQLException_Exception("SQLException...");
    }

}
