
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package fr.eseo.javaee.projet.visiteguidee;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-26T02:58:36.853+02:00
 * Generated source version: 3.2.2
 *
 */

@javax.jws.WebService(
                      serviceName = "ReservationVisiteService",
                      portName = "ReservationVisitePort",
                      targetNamespace = "http://visiteguidee.projet.javaee.eseo.fr/",
                      wsdlLocation = "http://localhost:8080/GestionVisites/services/ReservationVisitePort?wsdl",
                      endpointInterface = "fr.eseo.javaee.projet.visiteguidee.ReservationVisiteSEI")

public class ReservationVisitePortImpl implements ReservationVisiteSEI {

    private static final Logger LOG = Logger.getLogger(ReservationVisitePortImpl.class.getName());

    /* (non-Javadoc)
     * @see fr.eseo.javaee.projet.visiteguidee.ReservationVisiteSEI#reserverVisite(fr.eseo.javaee.projet.visiteguidee.Reservation arg0)*
     */
    public int reserverVisite(fr.eseo.javaee.projet.visiteguidee.Reservation arg0) throws SQLException_Exception   {
        LOG.info("Executing operation reserverVisite");
        System.out.println(arg0);
        try {
            int _return = -621577682;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SQLException_Exception("SQLException...");
    }

    /* (non-Javadoc)
     * @see fr.eseo.javaee.projet.visiteguidee.ReservationVisiteSEI#payerVisite(int arg0)*
     */
    public boolean payerVisite(int arg0) throws SQLException_Exception   {
        LOG.info("Executing operation payerVisite");
        System.out.println(arg0);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SQLException_Exception("SQLException...");
    }

    /* (non-Javadoc)
     * @see fr.eseo.javaee.projet.visiteguidee.ReservationVisiteSEI#trouverVisite(fr.eseo.javaee.projet.visiteguidee.Visite arg0)*
     */
    public java.util.List<fr.eseo.javaee.projet.visiteguidee.Visite> trouverVisite(fr.eseo.javaee.projet.visiteguidee.Visite arg0) throws SQLException_Exception   {
        LOG.info("Executing operation trouverVisite");
        System.out.println(arg0);
        try {
            java.util.List<fr.eseo.javaee.projet.visiteguidee.Visite> _return = new java.util.ArrayList<fr.eseo.javaee.projet.visiteguidee.Visite>();
            fr.eseo.javaee.projet.visiteguidee.Visite _returnVal1 = new fr.eseo.javaee.projet.visiteguidee.Visite();
            _returnVal1.setCodeVisite(-1394326422);
            fr.eseo.javaee.projet.visiteguidee.LocalDateTime _returnVal1DateVisite = new fr.eseo.javaee.projet.visiteguidee.LocalDateTime();
            _returnVal1.setDateVisite(_returnVal1DateVisite);
            java.util.List<java.lang.String> _returnVal1ListeAttributs = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnVal1ListeAttributsVal1 = "_returnVal1ListeAttributsVal-1312022875";
            _returnVal1ListeAttributs.add(_returnVal1ListeAttributsVal1);
            _returnVal1.getListeAttributs().addAll(_returnVal1ListeAttributs);
            _returnVal1.setPrix(0.13015449f);
            _returnVal1.setTypeDeVisite("TypeDeVisite-674568085");
            _returnVal1.setVille("Ville479776099");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SQLException_Exception("SQLException...");
    }

    /* (non-Javadoc)
     * @see fr.eseo.javaee.projet.visiteguidee.ReservationVisiteSEI#annulerVisite(int arg0)*
     */
    public boolean annulerVisite(int arg0) throws SQLException_Exception   {
        LOG.info("Executing operation annulerVisite");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new SQLException_Exception("SQLException...");
    }

}
