
package fr.eseo.javaee.projet.visiteguidee;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-26T02:58:36.780+02:00
 * Generated source version: 3.2.2
 *
 */
public final class ReservationVisiteSEI_ReservationVisitePort_Client {

    private static final QName SERVICE_NAME = new QName("http://visiteguidee.projet.javaee.eseo.fr/", "ReservationVisiteService");

    private ReservationVisiteSEI_ReservationVisitePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ReservationVisiteService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ReservationVisiteService ss = new ReservationVisiteService(wsdlURL, SERVICE_NAME);
        ReservationVisiteSEI port = ss.getReservationVisitePort();

        {
        System.out.println("Invoking reserverVisite...");
        fr.eseo.javaee.projet.visiteguidee.Reservation _reserverVisite_arg0 = new fr.eseo.javaee.projet.visiteguidee.Reservation();
        fr.eseo.javaee.projet.visiteguidee.Client _reserverVisite_arg0Client = new fr.eseo.javaee.projet.visiteguidee.Client();
        _reserverVisite_arg0Client.setAdresse("Adresse94716579");
        _reserverVisite_arg0Client.setCodePostal(195853604);
        _reserverVisite_arg0Client.setIdClient(1875179772);
        java.util.List<java.lang.String> _reserverVisite_arg0ClientListeAttributs = new java.util.ArrayList<java.lang.String>();
        java.lang.String _reserverVisite_arg0ClientListeAttributsVal1 = "_reserverVisite_arg0ClientListeAttributsVal256887600";
        _reserverVisite_arg0ClientListeAttributs.add(_reserverVisite_arg0ClientListeAttributsVal1);
        _reserverVisite_arg0Client.getListeAttributs().addAll(_reserverVisite_arg0ClientListeAttributs);
        _reserverVisite_arg0Client.setMail("Mail-14557586");
        _reserverVisite_arg0Client.setNom("Nom1071267461");
        _reserverVisite_arg0Client.setNumTelephone(-995754372);
        _reserverVisite_arg0Client.setPays("Pays-1518366063");
        _reserverVisite_arg0Client.setPrenom("Prenom991633985");
        _reserverVisite_arg0.setClient(_reserverVisite_arg0Client);
        _reserverVisite_arg0.setCodeReservation(2010852584);
        java.util.List<java.lang.String> _reserverVisite_arg0ListeAttributs = new java.util.ArrayList<java.lang.String>();
        java.lang.String _reserverVisite_arg0ListeAttributsVal1 = "_reserverVisite_arg0ListeAttributsVal177294891";
        _reserverVisite_arg0ListeAttributs.add(_reserverVisite_arg0ListeAttributsVal1);
        _reserverVisite_arg0.getListeAttributs().addAll(_reserverVisite_arg0ListeAttributs);
        _reserverVisite_arg0.setNombrePersonnes(-1483858386);
        _reserverVisite_arg0.setPaiementEffectue(false);
        fr.eseo.javaee.projet.visiteguidee.Visite _reserverVisite_arg0Visite = new fr.eseo.javaee.projet.visiteguidee.Visite();
        _reserverVisite_arg0Visite.setCodeVisite(-129836178);
        fr.eseo.javaee.projet.visiteguidee.LocalDateTime _reserverVisite_arg0VisiteDateVisite = new fr.eseo.javaee.projet.visiteguidee.LocalDateTime();
        _reserverVisite_arg0Visite.setDateVisite(_reserverVisite_arg0VisiteDateVisite);
        java.util.List<java.lang.String> _reserverVisite_arg0VisiteListeAttributs = new java.util.ArrayList<java.lang.String>();
        java.lang.String _reserverVisite_arg0VisiteListeAttributsVal1 = "_reserverVisite_arg0VisiteListeAttributsVal353281297";
        _reserverVisite_arg0VisiteListeAttributs.add(_reserverVisite_arg0VisiteListeAttributsVal1);
        _reserverVisite_arg0Visite.getListeAttributs().addAll(_reserverVisite_arg0VisiteListeAttributs);
        _reserverVisite_arg0Visite.setPrix(0.46675932f);
        _reserverVisite_arg0Visite.setTypeDeVisite("TypeDeVisite-1430431236");
        _reserverVisite_arg0Visite.setVille("Ville-302577077");
        _reserverVisite_arg0.setVisite(_reserverVisite_arg0Visite);
        try {
            int _reserverVisite__return = port.reserverVisite(_reserverVisite_arg0);
            System.out.println("reserverVisite.result=" + _reserverVisite__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking payerVisite...");
        int _payerVisite_arg0 = -161399573;
        try {
            boolean _payerVisite__return = port.payerVisite(_payerVisite_arg0);
            System.out.println("payerVisite.result=" + _payerVisite__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking trouverVisite...");
        fr.eseo.javaee.projet.visiteguidee.Visite _trouverVisite_arg0 = new fr.eseo.javaee.projet.visiteguidee.Visite();
        _trouverVisite_arg0.setCodeVisite(1728000731);
        fr.eseo.javaee.projet.visiteguidee.LocalDateTime _trouverVisite_arg0DateVisite = new fr.eseo.javaee.projet.visiteguidee.LocalDateTime();
        _trouverVisite_arg0.setDateVisite(_trouverVisite_arg0DateVisite);
        java.util.List<java.lang.String> _trouverVisite_arg0ListeAttributs = new java.util.ArrayList<java.lang.String>();
        java.lang.String _trouverVisite_arg0ListeAttributsVal1 = "_trouverVisite_arg0ListeAttributsVal533477124";
        _trouverVisite_arg0ListeAttributs.add(_trouverVisite_arg0ListeAttributsVal1);
        _trouverVisite_arg0.getListeAttributs().addAll(_trouverVisite_arg0ListeAttributs);
        _trouverVisite_arg0.setPrix(0.8910463f);
        _trouverVisite_arg0.setTypeDeVisite("TypeDeVisite-1998013173");
        _trouverVisite_arg0.setVille("Ville408360670");
        try {
            java.util.List<fr.eseo.javaee.projet.visiteguidee.Visite> _trouverVisite__return = port.trouverVisite(_trouverVisite_arg0);
            System.out.println("trouverVisite.result=" + _trouverVisite__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking annulerVisite...");
        int _annulerVisite_arg0 = -274437861;
        try {
            boolean _annulerVisite__return = port.annulerVisite(_annulerVisite_arg0);
            System.out.println("annulerVisite.result=" + _annulerVisite__return);

        } catch (SQLException_Exception e) {
            System.out.println("Expected exception: SQLException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
